language: go

go:
  - 1.6

sudo: false

before_script:
  - go vet ./...

install:
  # Add Godeps dependencies to GOPATH and PATH
  - go get github.com/tools/godep
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
